### PR TITLE
fixes #9 JWKS RSA marshalling of exponent panics

### LINKED ISSUE #9: Using NewKey w/ RSA key results in nil pointer exception
Using `NewKey` with an RSA key set results in a nil panic when the exponent is written to a temporary buffer. The write operation is attempting to use an empty string value on linked 134 in payload.go

### PR DESCRIPTION
**Pull request by andrewpmartinez**

### CODE REVIEW

File: payload.go [hunk 1]
```diff
@@ -131,7 +131,7 @@ func NewKey(keyId string, cert *x509.Certificate, chain []*x509.Certificate) (*K
 		ret.N = base64.RawURLEncoding.EncodeToString(rsaPubKey.N.Bytes())
 
 		buf := new(bytes.Buffer)
-		err := binary.Write(buf, binary.BigEndian, ret.E)
+		err := binary.Write(buf, binary.BigEndian, int32(rsaPubKey.E))
```
Comment (dovholuknf) [inline payload.go:134]: no test?

Comment (andrewpmartinez) [reply payload.go:134]: They are used in tests in the `ziti` project now, but I added tests here too.

**Review by dovholuknf — APPROVED** [review]
